# steps invovle in model building-
1.undestand the requirement/problem statement.


2.get the data/load the data.

3.data pre-processing/data cleaning(replacing nulls,rename,replacing,non-numeric values)

4.sampling(random sampling-train&test split)

5.building the model

6.test the model and check the model performance.

7.re-run the from some previous step

In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv('LungCapData.csv')
df


LungCap  Age  Height Smoke  Gender Caesarean
0      6.475    6    62.1    no    male        no
1     10.125   18    74.7   yes  female        no
2      9.550   16    69.7    no  female       yes
3     11.125   14    71.0    no    male        no
4      4.800    5    56.9    no    male        no
..       ...  ...     ...   ...     ...       ...
720    5.725    9    56.0    no  female        no
721    9.050   18    72.0   yes    male       yes
722    3.850   11    60.5   yes  female        no
723    9.825   15    64.9    no  female        no
724    7.100   10    67.7    no    male        no

[725 rows x 6 columns]

In [3]:
df.head()

LungCap  Age  Height Smoke  Gender Caesarean
0    6.475    6    62.1    no    male        no
1   10.125   18    74.7   yes  female        no
2    9.550   16    69.7    no  female       yes
3   11.125   14    71.0    no    male        no
4    4.800    5    56.9    no    male        no

In [4]:
#here target variable y is lungcap and others age and height is x

In [5]:
# data preprocessing

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 725 entries, 0 to 724
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   LungCap    725 non-null    float64
 1   Age        725 non-null    int64  
 2   Height     725 non-null    float64
 3   Smoke      725 non-null    object 
 4   Gender     725 non-null    object 
 5   Caesarean  725 non-null    object 
dtypes: float64(2), int64(1), object(3)
memory usage: 34.1+ KB


In [7]:
df.isnull().sum()

LungCap      0
Age          0
Height       0
Smoke        0
Gender       0
Caesarean    0
dtype: int64

In [8]:
df.Smoke.value_counts()

no     648
yes     77
Name: Smoke, dtype: int64

In [9]:
df.Smoke=df.Smoke.replace({"no":0,'yes':1})

In [10]:
df.Smoke.value_counts()

0    648
1     77
Name: Smoke, dtype: int64

In [11]:
df.Gender=df.Gender.replace({"male":0,'female':1})
df.Gender=df.Gender.

In [12]:
df.Caesarean=df.Caesarean.replace({"no":0,'yes':1})replace()

In [13]:
df.info()
#here we have convert the object in int datatype

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 725 entries, 0 to 724
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   LungCap    725 non-null    float64
 1   Age        725 non-null    int64  
 2   Height     725 non-null    float64
 3   Smoke      725 non-null    int64  
 4   Gender     725 non-null    int64  
 5   Caesarean  725 non-null    int64  
dtypes: float64(2), int64(4)
memory usage: 34.1 KB


In [14]:
#sampling
#first to use sampling we should import 

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
df_train,df_test=train_test_split(df,test_size=0.2)
df_train,df_test=train_test_split(df,test_size=0.2)

In [17]:
df_train.shape

(580, 6)

In [18]:
df_test.shape

(145, 6)

In [19]:
df.shape

(725, 6)

In [20]:
df_train_y=df_train.iloc[:,0]
df_test_y=df_test.iloc[:,0]

In [21]:
df_train_y

499     7.900
350     5.650
556     2.725
283     4.775
576    12.325
        ...  
215     5.850
245     3.825
13      6.000
483     9.675
423     7.800
Name: LungCap, Length: 580, dtype: float64

In [22]:
df_train_x=df_train.iloc[:,1::]
df_test_x=df_test.iloc[:,1::]

In [23]:
df_test_x.head()

Age  Height  Smoke  Gender  Caesarean
540    9    63.4      0       1          1
154   16    67.2      0       1          0
435   15    73.7      0       0          0
306   15    69.3      1       0          0
642   13    66.0      1       1          0

creating the model

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
linereg=LinearRegression()

In [26]:
linereg.fit(df_train_x,df_train_y)

LinearRegression()

In [32]:
Adj_Rsquare

0.8505864963172116

In [34]:
df_train_x.columns


Index(['Age', 'Height', 'Smoke', 'Gender', 'Caesarean'], dtype='object')

In [35]:
linereg.intercept_ # we will get betanot value



-10.893145908841689

predictions on train data

In [36]:
pred_train=linereg.predict(df_train_x)

In [37]:
pred_test=linereg.predict(df_test_x)

In [38]:
pred_train

array([ 8.10594875,  3.94116375,  4.36912774,  4.67919001, 12.30787358,
        8.40006534,  7.34749946, 10.18613671,  8.39496068,  6.54676226,
       12.62093522,  6.47417408, 11.53753847,  8.34729004,  8.13782882,
        9.48213921,  4.47183407,  3.30825931,  8.31937312,  4.62625961,
       11.21769567,  4.0128841 ,  6.49609225,  7.9804039 ,  8.23545675,
        3.82852179,  6.50513379,  6.17627571,  4.5203988 ,  2.86497694,
        4.55138478, 11.88297864,  7.07906566,  6.52255745, 10.76837113,
        5.20607854,  6.07943018,  8.11120851, 10.37985077,  2.60274042,
        9.2174872 ,  6.94900004, 10.26720881,  5.60095128, 11.45588248,
        9.19854215, 11.27288646,  7.2614778 ,  7.13425645,  4.49619399,
        5.25916405,  4.4674684 ,  5.50187163,  8.87343958,  7.87680348,
       10.17264993,  9.11252049,  9.0035052 ,  7.92310783, 11.45798776,
       10.84405464,  7.27351872,  8.11062462,  7.59020704,  9.08757668,
        8.03107392,  7.68494729,  7.90416278,  6.13251569,  4.39

In [39]:
pred_test

array([ 6.66481909,  8.97493472, 10.95966971,  9.1857885 ,  7.57834749,
        6.47188743,  6.60421344,  5.23480413, 11.32340137,  5.07375254,
        7.29472416, 10.53412121,  7.02629037,  6.25580015,  6.20271465,
        5.12005689,  9.24410751,  8.61346345,  8.85149515,  9.06250404,
        5.44668085,  7.04960109,  4.4674684 ,  9.46034989,  9.39385717,
       11.21980095,  6.34197692,  7.8217678 ,  3.49503711,  7.71575189,
        9.81940567,  9.68934005,  4.20281639, 10.75262397,  8.37360014,
        9.84587087,  9.98949881,  7.6340959 ,  6.6217922 , 10.0025568 ,
        6.48092897,  3.57217233,  5.36260937,  8.50518715,  5.10247812,
        7.6605611 ,  6.91816918, 12.09163119,  2.9906769 ,  9.11388678,
        8.21948481,  7.45125498,  6.52723332,  7.07622139,  4.49845437,
       10.11278327, 10.87801372, 10.43562545,  7.45125498,  3.33835119,
        6.31325133,  2.88014021,  9.71580525,  8.24353452,  4.44762925,
        9.76591765,  5.73853705, 12.93851763,  9.43146919, 10.32

In [40]:
#finding error that is actual value - predicted value

In [41]:
err_test=df_test_y-pred_test


In [42]:
err_test

540    0.135181
154    0.300065
435    0.340330
306   -0.710789
642    0.371653
         ...   
120   -1.031219
299    0.606009
373   -0.949385
239    1.361776
414   -0.225917
Name: LungCap, Length: 145, dtype: float64

In [27]:
Rsquare=linereg.score(df_train_x,df_train_y)

In [28]:
Rsquare #this means the our model is better...

0.85187676836974

In [29]:
N=df_train_x.shape[0]

In [30]:
K=df_train_x.shape[1]

In [31]:
Adj_Rsquare=1-(1-Rsquare)*(N-1)/(N-K-1)

In [43]:
mse=np.mean(np.square(err_test))
mse

1.0092356539868312

In [33]:
linereg.coef_ #it will display the beta values

array([ 0.15653082,  0.26465201, -0.60941235, -0.42102773, -0.20872223])

In [44]:
rsme=np.sqrt(mse)
rsme

1.0046072137839899

In [45]:
mape=np.mean(np.abs(err_test*100/df_test_y))
mape

13.795782985622688

In [ ]:
mape=np.mean